<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$itemMedia = $item->media();
$this->headScript()->appendFile('https://cdn.jsdelivr.net/npm/clipboard@2.0.6/dist/clipboard.min.js', 'text/javascript', ['defer' => 'defer']);
$this->headScript()->appendFile('https://cdn.jsdelivr.net/npm/file-saver@2.0.5/dist/FileSaver.min.js', 'text/javascript');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$itemSets = $item->itemSets();
$designerSets = [];
foreach ($itemSets as $key => $itemSet) {
  foreach ($itemSet->value('dcterms:type', ['all' => true]) as $itemSetType) {
    if (strtolower($itemSetType) == "designer") {
      $designerSets[] = $itemSet;
      unset($itemSets[$key]);
      break;
    }
  }
}
?>

<?php $this->trigger('view.show.before'); ?>

<?php if ($itemMedia): ?>
  <div class="container pt-3 pb-3 pt-md-5 pb-md-4">
    <div class="row" id="media-wrapper">
      <?php if ((count($itemMedia) > 1)): ?>
        <div class="col-md-11">
          <div class="media-embeds">
            <div class="tab-content" id="mediaTabContent">
              <?php $panel_id = 1; ?>
              <?php foreach ($itemMedia as $media): ?>
                <div class="tab-pane fade mirador-dark-theme <?php echo ($panel_id == 1 ? ' show active' : ''); ?>"
                  id="media-<?php echo $panel_id; ?>" role="tabpanel" aria-labelledby="media-<?php echo $panel_id; ?>-tab">
                  <?php echo $media->render(); ?>
                </div>
              <?php
                $panel_id++;
              endforeach;
              ?>
            </div>
          </div>
        </div>
        <div class="col-md-1 py-1 p-md-0 px-xl-2" id="media-sidebar">
          <ul class="nav align-items-center flex-md-column d-md-block" id="mediaTab" role="tablist">
            <?php $tab_id = 1; ?>
            <?php foreach ($itemMedia as $media): ?>
              <li class="nav-item p-md-0 mb-md-3" role="presentation">
                <button
                  class="nav-link text-secondary border-0 shadow-sm rounded p-0<?php echo ($tab_id == 1 ? ' active' : ''); ?>"
                  id="media-<?php echo $tab_id; ?>-tab" data-bs-toggle="tab" data-bs-target="#media-<?php echo $tab_id; ?>"
                  type="button" role="tab" aria-controls="media-<?php echo $tab_id; ?>"
                  aria-selected="<?php echo ($tab_id == 1 ? 'true' : 'false'); ?>">
                  <?php echo $this->thumbnail($media, 'medium', ['class' => 'rounded img-fluid', 'alt' => $media->displayTitle(), 'title' => $media->displayTitle(), 'data-bs-toggle' => 'tooltip']); ?>
                </button>
              </li>
            <?php
              $tab_id++;
            endforeach;
            ?>
          </ul>
          <button class="btn-arrow btnNext border-0 bg-transparent text-secondary d-none d-md-block mx-auto" type="button"
            aria-controls="mediaTabContent" aria-label="Next">
            <i class="fas fa-chevron-down" title="Next" aria-hidden="true">
            </i>
          </button>
        </div>
      <?php else: ?>
        <div class="col">
          <div class="media-embeds mirador-dark-theme">
            <?php foreach ($itemMedia as $media): ?>
              <?php echo $media->render(); ?>
            <?php endforeach; ?>
          </div>
        </div>
      <?php endif; ?>
    </div>
  </div>
<?php endif; ?>
<div class="container pt-2 pb-3 pt-md-4 pb-md-5" id="quick-details">
  <div class="row">
    <div class="col">
      <?php echo $this->pageTitle($item->displayTitle(null, ($filterLocale ? $lang : null)), 2); ?>
      <?php echo $this->ShareDownload($item); ?>
    </div>
  </div>
</div>
<hr>
<div class="container py-3 pt-md-5">
  <div class="row  justify-content-between">
    <div class="col-xl-10 col-xxl-9">

      <h3 class="mb-5 h5">
        <?php echo $translate('File Info'); ?>
      </h3>
      <?php if (count($designerSets) > 0): ?>
        <dl>
          <div class="property">
            <dt>
              <?php echo $translate('Designer/Brand'); ?>
            </dt>
            <?php foreach ($designerSets as $designerSet): ?>
              <dd class="value">
                <?php echo $escape($designerSet->displayTitle()); ?>
                <a href="<?php echo $this->url('site/search', ['site-slug' => $this->currentSite()->slug()], ['query' => ['limit' => ['item_set_dcterms_title' => [$designerSet->displayTitle()]]]]);; ?>" class="link-light ms-1" aria-label="Search for this designer/brand">
                  <i class="fas fa-search" title="Search for this designer/brand" aria-hidden="true"></i>
                </a>
                <?php foreach ($designerSet->value('dcterms:relation', ['all' => true, 'type' => 'uri']) as $relation): ?>
                  <?php if (strtolower($relation->value()) == 'wikipedia') : ?>
                    <a href="<?php echo $relation->uri(); ?>" target="_blank" class="link-light ms-1" aria-label="Read more about this designer/brand on Wikipedia">
                      <i class="fas fa-info-circle" title="Read more about this designer/brand on Wikipedia" aria-hidden="true"></i>
                    </a>
                    <?php break; ?>
                  <?php endif; ?>
                <?php endforeach; ?>
              </dd>
            <?php endforeach; ?>
          </div>
        </dl>
      <?php endif; ?>
      <?php if (count($itemSets) > 0): ?>
        <dl>
          <div class="property">
            <dt>
              <?php echo $translate('Collections'); ?>
            </dt>
            <?php foreach ($itemSets as $itemSet): ?>
              <dd class="value">
                <?php echo $escape($itemSet->displayTitle()); ?>
                <a href="<?php echo $this->url('site/search', ['site-slug' => $this->currentSite()->slug()], ['query' => ['limit' => ['item_set_dcterms_title' => [$itemSet->displayTitle()]]]]);; ?>" class="ms-1" aria-label="Search for this collection">
                  <i class="fas fa-search" title="Search for this collection" aria-hidden="true"></i>
                </a>
              </dd>
            <?php endforeach; ?>
          </div>
        </dl>
      <?php endif; ?>
      <?php echo $item->displayValues(); ?>
      <dl>
        <div class="property">
          <dt>
            <?php echo $translate('Citation'); ?>
          </dt>
          <dd class="value">
            <?php echo $this->CitationHelper($item); ?>
          </dd>
        </div>
      </dl>
    </div>
  </div>
</div>




<?php $this->trigger('view.show.after'); ?>