[info]
name = "FIT Designer Files"
version = "1.2"
author = "FIT Digital Initiatvies"
description = "Omeka-S theme for the FIT Designer Files. Built upon Bootstrap framework. Works with FITModule, and FIT-forked Solr modules, and FIT-forked MetadataBrowse."
;theme_link = ""
author_link = "https://github.com/fitnycdigitalinitiatives"
omeka_version_constraint = "^4.0.0"
helpers[] = "CitationHelper"
helpers[] = "QueryToStringHelper"
helpers[] = "ShareDownload"
helpers[] = "CreatorHelper"
helpers[] = "DateHelper"