<?php
/*
 * Copyright BibLibre, 2016
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

use Laminas\Uri\UriFactory;

$this->headScript()->appendFile($this->assetUrl('js/dateRange.js'));
$this->headScript()->appendFile($this->assetUrl('js/sortSelect.js'));
$queryFacets = [];
if (array_key_exists('limit', $queryParams)) {
  $queryFacets = $queryParams['limit'];
}
?>

<?php if (!empty($facets)): ?>

  <?php foreach ($facets as $name => $facetValues): ?>
    <?php
    $currentValues = [];
    if (array_key_exists($name, $queryFacets)) {
      foreach ($queryFacets[$name] as $queryFacet) {
        $currentValues[] = ['value' => $queryFacet, 'facetLink' => $this->facetLink($name, ['value' => $queryFacet, 'count' => null])];
      }
    }
    $placeholder = "Select a " . $this->facetLabel($name) . "...";
    $disabled = false;
    if ((count($currentValues) == 0) && (count($facetValues) == 0)) {
      $placeholder = "Not available for these results.";
      $disabled = true;
    }
    if ($name == "item_set_dcterms_title") {
      $hasClippingSlideOptions = false;
      $clippingSlideDisabled = false;
      $clippingSelected = false;
      $slideSelected = false;
      $slideLink = "";
      $clippingLink = "";
      foreach ($facetValues as $facetValueKey => $facetValue) {
        if ($facetValue["value"] == "Runway Slides" || $facetValue["value"] == "Designer Clippings") {
          $hasClippingSlideOptions = true;
          unset($facetValues[$facetValueKey]);
          $slideLink = $this->facetLink($name, ['value' => "Runway Slides", 'count' => null]);
          $clippingLink = $this->facetLink($name, ['value' => "Designer Clippings", 'count' => null]);
        }
      }
      foreach ($currentValues as $currentValueKey => $currentValue) {
        if ($currentValue['value'] == "Runway Slides") {
          $slideSelected = true;
          unset($currentValues[$currentValueKey]);
          $slideLink = $this->facetLink($name, ['value' => "Runway Slides", 'count' => null]);
          $uri = UriFactory::factory(htmlspecialchars_decode($this->facetLink($name, ['value' => "Designer Clippings", 'count' => null])));
          $thisArray = $uri->getQueryAsArray();
          unset($thisArray['limit'][$name][array_search('Runway Slides', $thisArray['limit'][$name])]);
          $clippingLink = $uri->setQuery($thisArray);
          if ($this->getCountForQuery($thisArray) == 0) {
            echo json_encode($thisArray);
            $clippingSlideDisabled = true;
          }
        } elseif ($currentValue['value'] == "Designer Clippings") {
          $clippingSelected = true;
          unset($currentValues[$currentValueKey]);
          $clippingLink = $this->facetLink($name, ['value' => "Designer Clippings", 'count' => null]);
          $uri = UriFactory::factory(htmlspecialchars_decode($this->facetLink($name, ['value' => "Runway Slides", 'count' => null])));
          $thisArray = $uri->getQueryAsArray();
          unset($thisArray['limit'][$name][array_search('Designer Clippings', $thisArray['limit'][$name])]);
          $slideLink = $uri->setQuery($thisArray);
          if ($this->getCountForQuery($thisArray) == 0) {
            $clippingSlideDisabled = true;
          }
        }
      }
      if (!$hasClippingSlideOptions && !$slideSelected && !$clippingSelected) {
        $clippingSlideDisabled = true;
        if ($firstItem) {
          foreach ($firstItem->itemSets() as $itemSet) {
            if ($itemSet->displayTitle() == "Runway Slides") {
              $slideSelected = true;
              break;
            } elseif ($itemSet->displayTitle() == "Designer Clippings") {
              $clippingSelected = true;
              break;
            }
          }
        }
      }
      if (isset($queryParams['item_set_id'])) {
        if (!is_array($queryParams['item_set_id'])) {
          $queryParams['item_set_id'] = [$queryParams['item_set_id']];
        }
        foreach ($queryParams['item_set_id'] as $thisItemSetId) {
          if ($queryItemSet = $this->api()->read('item_sets', $thisItemSetId)->getContent()) {
            $thisTitle = $queryItemSet->displayTitle();
            $thisFacetURI = UriFactory::factory(htmlspecialchars_decode($this->facetLink($name, ['value' => $thisTitle, 'count' => null])));
            $thisFacetArray = $thisFacetURI->getQueryAsArray();
            unset($thisFacetArray['limit'][$name][array_search($thisTitle, $thisFacetArray['limit'][$name])]);
            unset($thisFacetArray['item_set_id'][array_search($thisItemSetId, $thisFacetArray['limit'])]);
            $currentValues[] = ['value' => $thisTitle, 'facetLink' => $thisFacetURI->setQuery($thisFacetArray)];
            $disabled = false;
          }
        }
      }
    }
    ?>
    <div class="col-md-4 mb-3">
      <label for="<?php echo $this->facetLabel($name); ?>" class="form-label h5">
        <?php echo $this->facetLabel($name); ?>
      </label>
      <select id="<?php echo $this->facetLabel($name); ?>" class="facet-select form-select" data-placeholder="<?php echo $placeholder; ?>" autocomplete="off" multiple <?php echo $disabled ? "disabled" : ""; ?>>
        <?php foreach ($currentValues as $currentValue): ?>
          <option selected value="<?php echo $currentValue['facetLink']; ?>">
            <?php echo $currentValue['value']; ?>
          </option>
        <?php endforeach; ?>
        <?php $empty = true; ?>
        <?php foreach ($facetValues as $facetValue): ?>
          <?php $empty = false; ?>
          <option value="<?php echo $this->facetLink($name, $facetValue); ?>"
            data-count="<?php echo $facetValue["count"]; ?>">
            <?php echo $facetValue["value"]; ?>
          </option>
        <?php endforeach; ?>
        <?php if ($empty): ?>
          <option disabled value="">No additional <?php echo strtolower($this->facetLabel($name)); ?>s available for these
            results.
          </option>
        <?php endif; ?>
      </select>
    </div>
  <?php endforeach; ?>
  <div class="col-md-4 mb-3">
    <label class="form-label h5">Date</label>
    <?php
    $currentMin = 0;
    $currentMax = 0;
    $totalMin = 0;
    $totalMax = 0;
    $disabled = false;
    if ((!empty($dateFacetStats)) && (!empty($dateFacetStats["min"])) && (!empty($dateFacetStats["max"]))) {
      if (isset($queryParams['date_range_start']) && ($queryParams['date_range_start'][0]) && ($queryParams['date_range_start'][0] > $dateFacetStats["min"])) {
        $currentMin = $queryParams['date_range_start'][0];
      } else {
        $currentMin = $dateFacetStats["min"];
      }
      if (isset($queryParams['date_range_end']) && ($queryParams['date_range_end'][0]) && ($queryParams['date_range_end'][0] < $dateFacetStats["max"])) {
        $currentMax = $queryParams['date_range_end'][0];
      } else {
        $currentMax = $dateFacetStats["max"];
      }
      if (!empty($dateFacetStats["totalMin"])) {
        $totalMin = $dateFacetStats["totalMin"];
      } else {
        $totalMin = $currentMin;
      }
      if (!empty($dateFacetStats["totalMax"])) {
        $totalMax = $dateFacetStats["totalMax"];
      } else {
        $totalMax = $currentMin;
      }
    }
    if (($currentMin == $totalMin) && ($currentMax == $totalMax) && ($currentMin == $currentMax)) {
      $disabled = true;
    }
    $rangeURI = UriFactory::factory($this->dateRangeFacetURL());
    $rangeURIqueriesArray = $rangeURI->getQueryAsArray();
    ?>
    <div class="row g-2 g-xl-3">
      <div class="col"><select class="form-select date-select" id="dateRangeMin" name="date_range_start[]" aria-label="Date Range Start" <?php echo $disabled ? "disabled" : ""; ?>>
          <?php for ($i = $totalMin; $i <= $currentMax && $i != 0; ++$i): ?>
            <?php
            $rangeURIqueriesArray["date_range_start[]"] = $i;
            $rangeURIqueriesArray["date_range_end[]"] = $currentMax;
            $rangeURI->setQuery($rangeURIqueriesArray);
            ?>
            <option <?php echo $i == $currentMin ? "selected" : ""; ?> value="<?php echo $rangeURI; ?>">
              <?php echo $i; ?>
            </option>
          <?php endfor; ?>
        </select></div>
      <div class="col-auto"><span class="form-control-plaintext">to</span></div>
      <div class="col"><select class="form-select date-select" id="dateRangeMax" name="date_range_end[]" aria-label="Date Range End" <?php echo $disabled ? "disabled" : ""; ?>>
          <?php for ($i = $currentMin; $i <= $totalMax && $i != 0; ++$i): ?>
            <?php
            $rangeURIqueriesArray["date_range_start[]"] = $currentMin;
            $rangeURIqueriesArray["date_range_end[]"] = $i;
            $rangeURI->setQuery($rangeURIqueriesArray);
            ?>
            <option <?php echo $i == $currentMax ? "selected" : ""; ?> value="<?php echo $rangeURI; ?>">
              <?php echo $i; ?>
            </option>
          <?php endfor; ?>
        </select></div>

    </div>
  </div>
  <div class="col-md-4 mb-3">
    <label class="form-label h5">Sort</label>
    <select id="sort" class="sort-select form-select" autocomplete="off">
      <?php foreach ($sortOptions as $value => $sortOptionLabel): ?>
        <option value="<?php echo $value; ?>" <?php echo $value == $currentSort ? "selected" : ""; ?>>
          <?php echo $sortOptionLabel; ?>
        </option>
      <?php endforeach; ?>
    </select>
  </div>
  <div class="col-12">
    <div class="row justify-content-between">
      <div class="col-auto">
        <label class="form-label h5 d-block">Show Only</label>
        <div class="form-check form-check-inline">
          <input class="form-check-input clipping-slide-option" type="checkbox" name="inlineRadioOptions" id="clippingoption"
            value="<?php echo $clippingLink; ?>" <?php echo $clippingSelected ? "checked" : ""; ?> <?php echo $clippingSlideDisabled ? "disabled" : ""; ?> autocomplete='off'>
          <label class="form-check-label" for="clippingoption">Designer Clippings</label>
        </div>
        <div class="form-check form-check-inline">
          <input class="form-check-input clipping-slide-option" type="checkbox" name="inlineRadioOptions" id="slideoption"
            value="<?php echo $slideLink; ?>" <?php echo $slideSelected ? "checked" : ""; ?> <?php echo $clippingSlideDisabled ? "disabled" : ""; ?> autocomplete='off'>
          <label class="form-check-label" for="slideoption">Runway Slides</label>
        </div>
      </div>
      <?php if ($queryParams): ?>
        <div class="col-auto">
          <button id="reset-filters" class="p-0 bg-transparent border-0 link-light fs-6">
            Reset filters
          </button>
        </div>
      <?php endif; ?>
    </div>
  </div>
<?php endif; ?>