<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->appendAttribute('lang', $this->lang())->appendAttribute('class', 'h-100');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($site->title())->setSeparator(' · ');
$this->headLink(['rel' => 'icon', 'type' => 'image/x-icon', 'href' => $this->assetUrl('img/favicon.ico')], 'PREPEND')
  ->prependStylesheet('https://cdn.jsdelivr.net/npm/tom-select@2.3.1/dist/css/tom-select.bootstrap5.min.css')
  ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.8.1/nouislider.min.css', 'screen', null, ['integrity' => 'sha512-qveKnGrvOChbSzAdtSs8p69eoLegyh+1hwOMbmpCViIwj7rn4oJjdmMvWOuyQlTOZgTlZA0N2PXA7iA8/2TUYA==', 'crossorigin' => 'anonymous'])
  ->prependStylesheet($this->assetUrl('css/style.css'))
  ->prependStylesheet('https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/all.min.css', 'screen', null, ['integrity' => 'sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4=', 'crossorigin' => 'anonymous'])
  ->prependStylesheet('https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css', 'screen', null, ['integrity' => 'sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH', 'crossorigin' => 'anonymous']);
$this->headScript()
  ->prependFile('https://cdn.jsdelivr.net/npm/tom-select@2.3.1/dist/js/tom-select.complete.min.js', 'text/javascript')
  ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.8.1/nouislider.min.js', 'text/javascript', ['integrity' => 'sha512-g/feAizmeiVKSwvfW0Xk3ZHZqv5Zs8PEXEBKzL15pM0SevEvoX8eJ4yFWbqakvRj7vtw1Q97bLzEpG2IVWX0Mg==', 'crossorigin' => 'anonymous'])
  ->prependFile($this->assetUrl('js/advanced-search.js', 'Omeka'))
  ->prependFile($this->assetUrl('js/theme.js'))
  ->prependFile($this->assetUrl('js/global.js', 'Omeka'))
  ->prependFile('https://unpkg.com/infinite-scroll@4.0.1/dist/infinite-scroll.pkgd.min.js', 'text/javascript')
  ->prependFile('https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js', 'text/javascript', ['integrity' => 'sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz', 'crossorigin' => 'anonymous'])
  ->prependFile('https://code.jquery.com/jquery-3.6.0.min.js', 'text/javascript', ['integrity' => 'sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=', 'crossorigin' => 'anonymous']);
$this->trigger('view.layout');
$userBar = $this->userBar('common/theme-site-slug-as-domain-user-bar');
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>

<head>
  <!-- Google tag (gtag.js) -->
  <!-- <script async src="https://www.googletagmanager.com/gtag/js?id=G-G2C4GN53HX"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'G-G2C4GN53HX');
  </script> -->
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headTitle(); ?>
  <?php echo $this->headLink(); ?>
  <?php echo $this->headStyle(); ?>
  <?php echo $this->headScript(); ?>
</head>

<?php echo $this->htmlElement('body')->appendAttribute('class', 'd-flex flex-column h-100'); ?>
<a class="visually-hidden-focusable" href="#content">
  <?php echo $this->translate('Skip to main content'); ?>
</a>

<header class="flex-shrink-0">
  <?php if ($userBar) : ?>
    <nav class="navbar navbar-expand-md d-none d-md-block user-info">
      <div class="container-fluid">
        <div class="navbar-collapse">
          <?php echo $userBar; ?>
        </div>
      </div>
    </nav>
  <?php endif; ?>
  <div class="container pt-5 d-none d-md-block">
    <div class="row justify-content-center">
      <div class="col-auto">
        <a href="/" class="logo text-light text-decoration-none">
          <h1 class="visually-hidden">
            <?php echo $escape($site->title()); ?>
          </h1>
          <img src="<?php echo $this->assetUrl('img/designer-files-logo.png'); ?>" title="Logo"
            alt="The FIT Designer Files">
        </a>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-expand-md navbar-light main-navbar" data-bs-theme="dark">
    <div class="container">
      <a class="navbar-brand me-1 d-md-none" href="<?php echo $site->url(); ?>">
        <img src="<?php echo $this->assetUrl('img/designer-files-logo.png'); ?>" alt="The FIT Designer Files">
      </a>
      <button class="navbar-toggler p-0 border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <?php echo $site->publicNav()->menu()->renderPartialWithParams(['site' => $site,], null, 'common/bootstrap-navigation.phtml'); ?>
        <?php if ($userBar) : ?>
          <div class="d-md-none user-info">
            <?php echo $userBar; ?>
          </div>
        <?php endif; ?>

      </div>
    </div>
  </nav>
</header>
<div class="flex-shrink-0" id="content" role="main">
  <?php echo $this->content; ?>
</div>
<footer class="footer mt-auto py-3 py-md-5 border-top">
  <div class="container text-center">
    <div class="row justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-5">
        <a href="https://www.fitnyc.edu/">
          <img class="mb-3" src="<?php echo $this->assetUrl('img/wordmark-white-1-line.png'); ?>" alt="FIT SUNY Logo"
            id="fit-logo">
        </a>
        <p class="small">
          ©
          <?php echo date("Y"); ?> Fashion Institute of Technology
          <br>
          All rights reserved.
        </p>
        <p class="text-left">This site is an initiative of the FIT Library.</p>
        <ul class="list-inline mb-0">
          <li class="list-inline-item"><a class="link-light" href="https://www.fitnyc.edu/academics/library/"
              aria-label="FIT Library Homepage"><i class="fas fa-home" aria-hidden="true"
                title="FIT Library Homepage"></i><span class="sr-only">FIT Library Homepage</span></a></li>
          <li class="list-inline-item"><a class="link-light" href="https://www.facebook.com/FITLibrary"
              aria-label="FIT Library Facebook"><i class="fab fa-facebook" aria-hidden="true"
                title="FIT Library Facebook"></i><span class="sr-only">FIT Library Facebook</span></a></li>
          <li class="list-inline-item"><a class="link-light" href="https://x.com/FITLibrary"
              aria-label="FIT Library X">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" style="width: 1em;height: 1em;vertical-align: -0.125em;"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.-->
                <path fill="currentColor" d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z" />
              </svg>
              <span class="sr-only">FIT Library X</span></a></li>
          <li class="list-inline-item"><a class="link-light" href="https://www.tiktok.com/@fitnyclibrary"
              aria-label="FIT Library TikTok"><i class="fab fa-tiktok" aria-hidden="true"
                title="FIT Library TikTok"></i><span class="sr-only">FIT Library TikTok</span></a></li>
          <li class="list-inline-item"><a class="link-light" href="https://www.instagram.com/fitnyclibrary/"
              aria-label="FIT Library Instagram"><i class="fab fa-instagram" aria-hidden="true"
                title="FIT Library Instagram"></i><span class="sr-only">FIT Library Instagram</span></a></li>
          <li class="list-inline-item"><a class="link-light" href="https://www.youtube.com/channel/UCtODQSjWRpZwy_pZYEgiBvw"
              aria-label="FIT Library YouTube"><i class="fab fa-youtube" aria-hidden="true"
                title="FIT Library YouTube"></i><span class="sr-only">FIT Library YouTube</span></a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>
</body>

</html>